name: 'Backlog-GitHub Sync Action'
description: 'Sync GitHub PRs to Backlog issues'

inputs:
  BACKLOG_API_KEY:
    description: 'Your Backlog API key'
    required: true
  BACKLOG_SPACE_NAME:
    description: 'Your Backlog space name'
    required: true
  BACKLOG_SPACE_DOMAIN:
    description: 'Your Backlog space domain'
    required: true
  BACKLOG_PROJECT_KEY:
    description: 'Your Backlog project key'
    required: true
  BACKLOG_CUSTOM_FIELD_ID:
    description: 'Your Backlog custom field ID'
    required: true
  PR_BODY:
    description: 'The body of the pull request'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  steps:
    - name: Check for Backlog URL
      id: check_url
      shell: bash
      run: |
        if echo "${{ inputs.PR_BODY }}" | grep -q "https://${{ inputs.BACKLOG_SPACE_NAME }}.${{ inputs.BACKLOG_SPACE_DOMAIN }}/"; then
          echo "CONTAINS_BACKLOG_URL=true" >> $GITHUB_OUTPUT
        else
          echo "CONTAINS_BACKLOG_URL=false" >> $GITHUB_OUTPUT
        fi

    - name: Run sync if Backlog URL exists
      if: steps.check_url.outputs.CONTAINS_BACKLOG_URL == 'true'
      env:
        BACKLOG_API_KEY: ${{ inputs.BACKLOG_API_KEY }}
        BACKLOG_SPACE_NAME: ${{ inputs.BACKLOG_SPACE_NAME }}
        BACKLOG_PROJECT_KEY: ${{ inputs.BACKLOG_PROJECT_KEY }}
        BACKLOG_CUSTOM_FIELD_ID: ${{ inputs.BACKLOG_CUSTOM_FIELD_ID }}
