name: 'Backlog-GitHub Sync Action'
description: 'Sync GitHub PRs to Backlog issues'

inputs:
  BACKLOG_API_KEY:
    description: 'Your Backlog API key'
    required: true
  BACKLOG_SPACE_NAME:
    description: 'Your Backlog space name'
    required: true
  BACKLOG_SPACE_DOMAIN:
    description: 'Your Backlog space domain'
    required: true
  BACKLOG_PROJECT_KEY:
    description: 'Your Backlog project key'
    required: true
  BACKLOG_CUSTOM_FIELD_ID:
    description: 'Your Backlog custom field ID'
    required: true
  PR_BODY:
    description: 'The body of the pull request'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Check Backlog URL
      id: check_url
      shell: bash
      run: |
        if grep -q "https://${{ inputs.BACKLOG_SPACE_NAME }}.${{ inputs.BACKLOG_SPACE_DOMAIN }}/" <<< "${{ inputs.PR_BODY }}"; then
          echo "Backlog URLが見つかりました。処理を続行します。"
        else
          echo "Backlog URLが見つかりません。アクションを終了します。"
          exit 0
        fi

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: 'pj8/github-backlog-sync'
        ref: 'ubuntu-latest-node'

    - name: Install dependencies
      shell: bash
      run: |
        npm ci

    - name: Run sync
      shell: bash
      run: node index.js
      env:
        BACKLOG_API_KEY: ${{ inputs.BACKLOG_API_KEY }}
        BACKLOG_SPACE_NAME: ${{ inputs.BACKLOG_SPACE_NAME }}
        BACKLOG_SPACE_DOMAIN: ${{ inputs.BACKLOG_SPACE_DOMAIN }}
        BACKLOG_PROJECT_KEY: ${{ inputs.BACKLOG_PROJECT_KEY }}
        BACKLOG_CUSTOM_FIELD_ID: ${{ inputs.BACKLOG_CUSTOM_FIELD_ID }}
